/** Auto-generated by scripts/optimize-images.mjs — do not edit */
export const imageManifest = {
  "alcazaba": {
    "base": "alcazaba",
    "width": 3840,
    "height": 2488,
    "fallbackWidth": 800,
    "fallbackHeight": 518,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "alhambra": {
    "base": "alhambra",
    "width": 2112,
    "height": 2354,
    "fallbackWidth": 1920,
    "fallbackHeight": 2140,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "caminito": {
    "base": "caminito",
    "width": 1799,
    "height": 1196,
    "fallbackWidth": 1799,
    "fallbackHeight": 1196,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "coast": {
    "base": "coast",
    "width": 800,
    "height": 600,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "compare": {
    "base": "compare",
    "width": 3210,
    "height": 2046,
    "fallbackWidth": 1920,
    "fallbackHeight": 1224,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "cruise-port": {
    "base": "cruise-port",
    "width": 1248,
    "height": 1008,
    "fallbackWidth": 1248,
    "fallbackHeight": 1008,
    "widths": [
      320,
      480,
      640,
      800,
      960
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "family": {
    "base": "family",
    "width": 1248,
    "height": 1008,
    "fallbackWidth": 800,
    "fallbackHeight": 646,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "food": {
    "base": "food",
    "width": 1024,
    "height": 768,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "granada": {
    "base": "granada",
    "width": 320,
    "height": 240,
    "fallbackWidth": 320,
    "fallbackHeight": 240,
    "widths": [
      320
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hero-home": {
    "base": "hero-home",
    "width": 3210,
    "height": 2046,
    "fallbackWidth": 1920,
    "fallbackHeight": 1224,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "historic": {
    "base": "historic",
    "width": 2484,
    "height": 3583,
    "fallbackWidth": 800,
    "fallbackHeight": 1154,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "mijas": {
    "base": "mijas",
    "width": 2008,
    "height": 3000,
    "fallbackWidth": 800,
    "fallbackHeight": 1195,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "og-default": {
    "base": "og-default",
    "width": 3000,
    "height": 1169,
    "fallbackWidth": 1920,
    "fallbackHeight": 748,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ],
    "og": {
      "width": 1200,
      "height": 630
    },
    "ogSrc": "/images/opt/og-default-og1200.jpg"
  },
  "photography": {
    "base": "photography",
    "width": 1728,
    "height": 2304,
    "fallbackWidth": 1728,
    "fallbackHeight": 2304,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "private": {
    "base": "private",
    "width": 3370,
    "height": 4115,
    "fallbackWidth": 800,
    "fallbackHeight": 977,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "ronda": {
    "base": "ronda",
    "width": 1728,
    "height": 2304,
    "fallbackWidth": 1728,
    "fallbackHeight": 2304,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "walking": {
    "base": "walking",
    "width": 3840,
    "height": 2880,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "white-villages": {
    "base": "white-villages",
    "width": 3210,
    "height": 2046,
    "fallbackWidth": 800,
    "fallbackHeight": 510,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "wine": {
    "base": "wine",
    "width": 768,
    "height": 1024,
    "fallbackWidth": 768,
    "fallbackHeight": 1024,
    "widths": [
      320,
      480,
      640
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  }
} as const;

export type ImageManifestEntry = (typeof imageManifest)[keyof typeof imageManifest];
